### ISSUE TITLE
Unable to find PS256 in JsonWebKeySignatureAlgorithm

### ISSUE THREAD

**Issue by Matheshgit** [Azure/azure-keyvault-java#11]
Trying to use PSS padding for Signature but unable to find PS256 in JsonWebKeySignatureAlgorithm
Azure Key Vault REST API (https://docs.microsoft.com/en-us/rest/api/keyvault/sign/sign) got many values that are missing in JsonWebKeySignatureAlgorithm. 
Note: Microsoft Azure API accept String for algorithm,

**Comment by RandalliLama** [comment]
@Matheshgit You can pass "PS256" in to the JsonWebKeySignatureAlgorithm constructor and that should work just fine.  The predefined values are just convenience constants.

**Comment by RandalliLama** [comment]
I've added new constants for the PSS algorithms.  This change will go out in the next release which should happen in a few weeks.
