### ISSUE TITLE
Vulnerable Dependency in com.microsoft.azure:adal4j

### ISSUE THREAD

**Issue by aabashkin** [Azure/azure-keyvault-java#16]
Latest POM has adal4j version 1.1.2 - https://github.com/Azure/azure-keyvault-java/blob/dev/pom.xml#L129

adal4j depends on com.nimbusds:oauth2-oidc-sdk 4.5 , which depends on com.nimbusds:nimbus-jose-jwt 3.1.2, which depends on org.bouncycastle:bcprov-jdk15on 1.51.

The 1.51 version of bouncycastle has a vulnerability that was resolved in 1.52 : http://www.bouncycastle.org/releasenotes.html (A badly formed issuer in a X.509 certificate could cause a null pointer exception in X509CertificateHolder.toString(). This has been fixed)

Solution:

**Upgrade to com.microsoft.azure:adal4j version 1.3+**

Explanation:

- com.nimbusds:nimbus-jose-jwt version 3.10 and higher uses Bouncy Castle 1.52+[https://mvnrepository.com/artifact/com.nimbusds/nimbus-jose-jwt/3.10]

- com.nimbusds:oauth2-oidc-sdk version 5.0 and higher uses nimbus-jose-jwt versions 3.10+ [http://central.maven.org/maven2/com/nimbusds/oauth2-oidc-sdk/5.0/oauth2-oidc-sdk-5.0.pom]

- com.microsoft.azure:adal4j version 1.3 and higher uses com.nimbusds:oauth2-oidc-sdk 5.0+

**Comment by RandalliLama** [comment]
This is now updated in the dev branch and will move to master in the next few weeks.  There is no actual vulnerability because the dependency on ADAL is only in the tests.
