### ISSUE TITLE
Inconsistent parameters expectation between ISignatureTransform implementations

### ISSUE THREAD

**Issue by logachev** [Azure/azure-keyvault-java#39]
There are two implementations of ISignatureTransform interface in this library: rs256 and ecdsa.

RS256 has an issue that it accepts only 256-bytes valus, so user has to hash his data before sign()\verify() call.
ECDSA uses java security library and just pass digest to it, so it expects raw data instead of its hash.

Ideally, RS256 should be fixed to accept raw data, but it is a breaking change - if someone relies on current behavior, its very easy to overlook this change. It might lead to the regression in users code.

**Comment by tiffanyachen** [comment]
fixed in cd98607
